//! # IO-Link Event Handler Module
//!
//! This module defines traits and types for handling event signaling and memory management in IO-Link devices.
//! It provides interfaces for triggering and confirming events, as well as structures for encoding event qualifiers
//! and status codes according to the IO-Link specification.
//!
//! ## Key Traits
//! - [`DlEventTriggerConf`]: Handles DL_EventTrigger confirmation.
//! - [`DlEventReq`]: Handles DL_Event requests and triggers.
//!
//! ## Key Types
//! - [`StatusCodeType1`], [`StatusCodeType2`]: Bitfield structures for event status codes.
//! - [`EventQualifier`]: Bitfield structure for event qualifier encoding.
//! - [`EventEntry`]: Represents a single event entry in event memory.
//! - [`EhConfState`]: Configuration state for the event handler.
//!
//! ## Specification Reference
//! - IO-Link v1.1.4, Section 7.2.1.17 (DL_EventTrigger)
//! - Section 8.3.3, Figure 56 – State machine of the Device Event handler
//! - Annex A.6 – Event qualifier and status code encoding
//!
//! This module is intended for use in IO-Link device implementations to manage event signaling,
//! memory, and status reporting in compliance with the protocol.

use crate::custom::IoLinkResult;

/// Trait for handling the DL_EventTrigger service as specified in section 7.2.1.17.
///
/// The DL_EventTrigger request initiates Event signaling and freezes the Event memory within the Data Link (DL).
/// Confirmation is returned after the activated Events have been processed. Additional DL_EventTrigger requests
/// are ignored until the previous one has been confirmed. This service does not require any parameters.
///
/// See: Event flag in Figure A.3, sections 7.3.8, 8.3.3, and Figure 66 of the specification.
pub trait DlEventTriggerConf {
    /// Handle the DL_EventTrigger confirmation.
    /// Event is been confirmed from the master side.
    fn event_trigger_conf(&mut self) -> IoLinkResult<()>;
}

/// Trait for handling DL_Event service requests as specified in IO-Link.
///
/// The DL_Event service indicates a pending status or error information.
/// The cause for an Event is located in a Device and the Device application triggers the Event transfer.
///
/// # Methods
///
/// - `dl_event_req`: Handles the DL_Event request, transmitting event entries.
///   - `event_count`: Number of event entries.
///   - `event_entries`: Slice of [`EventEntry`] containing event details.
///   - Returns [`IoLinkResult<()>`] indicating success or failure.
///
/// - `dl_event_trigger_req`: Triggers the DL_Event request.
///   - Returns [`IoLinkResult<()>`] indicating success or failure.
///
/// # Parameters (as per IO-Link specification)
/// - Instance: Indicates the Event source (Application).
/// - Type: Indicates the Event category (ERROR, WARNING, NOTIFICATION).
/// - Mode: Indicates the Event mode (SINGLESHOT, APPEARS, DISAPPEARS).
/// - EventCode: 16-bit code identifying the Event.
/// - EventsLeft: Number of unprocessed Events.
///
/// See IO-Link specification Table 30 – DL_Event for details.
pub trait DlEventReq {
    /// - `dl_event_req`: Handles the DL_Event request, transmitting event entries.
    ///   - `event_count`: Number of event entries.
    ///   - `event_entries`: Slice of [`EventEntry`] containing event details.
    ///   - Returns [`IoLinkResult<()>`] indicating success or failure.
    fn dl_event_req(&mut self, event_count: u8, event_entries: &[EventEntry]) -> IoLinkResult<()>;

    /// - `dl_event_trigger_req`: Triggers the DL_Event request.
    ///   - Returns [`IoLinkResult<()>`] indicating success or failure.
    fn dl_event_trigger_req(&mut self) -> IoLinkResult<()>;
}

use bitfields::bitfield;
use iolinke_macros::bitfield_support;

/// StatusCodeType1 (no details)
///
/// See IO-Link Spec v1.1.4, section A.6.2 and Figure A.21.
/// ```text
/// Structure (bit layout, MSB to LSB):
///  ┌───────┬───────────┬────────┬───────────────┐
///  │  B7   │    B6     │  B5    │   B4..B0      │
///  ├───────┼───────────┼────────┼───────────────┤
///  │Event  │   PD      │Reserved│ Event Code    │
///  │Details│  Valid    │        │   (type 1)    │
///  └───────┴───────────┴────────┴───────────────┘
/// ```
/// - Bits 0..=4: `event_code`
///     - EventCode (type 1), see Table A.16 for mapping to type 2.
///     - Coding of this data structure is listed in Table A.16.
/// - Bit 5: `reserved`
///     - Reserved, must be set to zero.
/// - Bit 6: `pd_valid`
///     - PD Invalid indicator (used in legacy protocol, see [B1] for PDInvalid indication).
/// - Bit 7: `event_details`
///     - Indicates that no detailed Event information is available. Always set to zero in StatusCodeType1.
///
/// NOTE: StatusCode type 1 is only used in Events generated by legacy devices.
///
/// # Example
/// ```text
///  7   6   5   4   3   2   1   0
/// [0 | 1 | 0 | event_code (5 bits) ]
/// ```
///
#[bitfield(u8)]
#[derive(Clone, Copy, PartialEq, Eq)]
pub struct StatusCodeType1 {
    /// Bit 7: Event Details (must be 0, no details available)
    #[bits(1)]
    event_details: u8,
    /// Bit 6: PD Valid (legacy usage for PDInvalid indication)
    #[bits(1)]
    pd_valid: bool,
    /// Bit 5: Reserved (must be 0)
    #[bits(1)]
    reserved: bool,
    /// Bits 0..=4: Event Code (type 1)
    #[bits(5)]
    event_code: u8,
}

/// StatusCodeType2 (with details)
///
/// See IO-Link Spec v1.1.4, section A.6.3 and Figure A.22, A.23.
///
/// ```text
/// Structure (bit layout, MSB to LSB):
///  ┌───────┬──────────┬───────────────┐
///  │  B7   │   B6     │   B5..B0      │
///  ├───────┼──────────┼───────────────┤
///  │Event  │ Reserved │ Activated     │
///  │Details│          │ Event Slots   │
///  └───────┴──────────┴───────────────┘
/// ```
///
/// - Bit 7: `event_details`
///     - This bit indicates that detailed Event information is available. It shall always be set in StatusCodeType2.
/// - Bit 6: `reserved`
///     - This bit is reserved and shall be set to zero.
/// - Bits 0..=5: `activated_event_slotN`
///     - Each bit is linked to an Event in the memory (see A.3.8.1).
///     - Bit 0: Event 1, Bit 1: Event 2, ..., Bit 5: Event 6.
///     - A bit value of '1' indicates that the corresponding EventQualifier and EventCode have been entered in valid formats in the memory.
///     - A bit value of '0' indicates an invalid entry.
///
/// # Example
/// ```text
///  7   6   5   4   3   2   1   0
/// [1 | 0 | activated_event_slot6 | ... | activated_event_slot1 ]
/// ```
///
#[bitfield(u8)]
#[derive(Clone, Copy, PartialEq, Eq)]
pub struct StatusCodeType2 {
    /// Bit 7: Event Details (shall always be set in StatusCodeType2)
    #[bits(1)]
    event_details: u8,
    /// Bit 6: Reserved (shall be set to zero)
    #[bits(1)]
    reserved: u8,
    /// Bit 5: Activated Event Slot 6
    #[bits(1)]
    activated_event_slot6: u8,
    /// Bit 4: Activated Event Slot 5
    #[bits(1)]
    activated_event_slot5: u8,
    /// Bit 3: Activated Event Slot 4
    #[bits(1)]
    activated_event_slot4: u8,
    /// Bit 2: Activated Event Slot 3
    #[bits(1)]
    activated_event_slot3: u8,
    /// Bit 1: Activated Event Slot 2
    #[bits(1)]
    activated_event_slot2: u8,
    /// Bit 0: Activated Event Slot 1
    #[bits(1)]
    activated_event_slot1: u8,
}

/// EventQualifier (see IO-Link Spec V1.1.4, §A.6.4, Fig. A.24)
///
/// ```text
/// Structure of the EventQualifier byte:
///  ┌───────┬───────┬───────┬────────────┐
///  │ 7   6 │ 5   4 │   3   │ 2   1   0  │
///  │ MODE  │ TYPE  │ SOURCE│  INSTANCE  │
///  └───────┴───────┴───────┴────────────┘
/// ```
///
/// - Bits 0..=2: `INSTANCE`
///     - Indicates the particular source (instance) of an Event thus relating its evaluation on the receiver side.
///     - Permissible values (see Table A.17):
///         - 0: Unknown
///         - 1..=3: Reserved
///         - 4: Application
///         - 5: System
///         - 6..=7: Reserved
///
/// - Bit 3: `SOURCE`
///     - Indicates the source of the Event (see Table A.18):
///         - 0: Device (remote)
///         - 1: Master/Port
///
/// - Bits 4..=5: `TYPE`
///     - Indicates the Event category (see Table A.19):
///         - 0: Reserved
///         - 1: Notification
///         - 2: Warning
///         - 3: Error
///
/// - Bits 6..=7: `MODE`
///     - Indicates the Event mode (see Table A.20):
///         - 0: Single
///         - 1: Multiple
///         - 2: Latched
///         - 3: Reserved
///
#[bitfield(u8)]
#[derive(Clone, Copy, PartialEq, Eq)]
pub struct EventQualifier {
    /// Bits 6..=7: MODE (Event mode)
    #[bits(2)]
    pub eq_mode: EventMode,
    /// Bits 4..=5: TYPE (Event category)
    #[bits(2)]
    pub eq_type: EventType,
    /// Bit 3: SOURCE (Event source)
    #[bits(1)]
    pub eq_source: EventSource,
    /// Bits 0..=2: INSTANCE (Event instance)
    #[bits(3)]
    pub eq_instance: EventInstance,
}

/// EventQualifier INSTANCE field (Bits 0..=2)
/// Indicates the particular source (instance) of an Event, relating to its evaluation on the receiver side.
/// See Table A.17 – Values of INSTANCE:
/// - 0: Unknown
/// - 1..=3: Reserved
/// - 4: Application
/// - 5: System
/// - 6..=7: Reserved
#[bitfield_support]
#[repr(u8)]
#[derive(Clone, Copy, PartialEq, Eq)]
pub enum EventInstance {
    /// 0: Unknown instance
    Unknown = 0,
    // 1..=3: Reserved
    /// 4: Application instance
    Application = 4,
    /// 5: System instance
    System = 5,
    // 6..=7: Reserved
}

impl EventInstance {
    /// Returns the default EventInstance value (`Unknown`).
    pub const fn new() -> Self {
        Self::Unknown
    }
}

/// EventQualifier SOURCE field (Bit 3)
/// Indicates the source of the Event.
/// See Table A.18 – Values of SOURCE:
/// - 0: Device (remote)
/// - 1: Master/Port
#[bitfield_support]
#[repr(u8)]
#[derive(Clone, Copy, PartialEq, Eq)]
pub enum EventSource {
    /// 0: Device (remote)
    Device = 0,
    /// 1: Master/Port
    Master = 1,
}

impl EventSource {
    /// Returns the default EventSource value (`Device`).
    pub const fn new() -> Self {
        Self::Device
    }
}

/// EventQualifier TYPE field (Bits 4..=5)
/// Indicates the Event category.
/// See Table A.19 – Values of TYPE:
/// - 0: Reserved
/// - 1: Notification
/// - 2: Warning
/// - 3: Error
#[bitfield_support]
#[repr(u8)]
#[derive(Clone, Copy, PartialEq, Eq)]
pub enum EventType {
    // 0: Reserved
    /// 1: Notification
    Notification = 1,
    /// 2: Warning
    Warning = 2,
    /// 3: Error
    Error = 3,
}

impl EventType {
    /// Returns the default EventType value (`Notification`).
    pub const fn new() -> Self {
        Self::Notification
    }
}

/// EventQualifier MODE field (Bits 6..=7)
/// Indicates the Event mode.
/// See Table A.20 – Values of MODE:
/// - 0: Single
/// - 1: Multiple
/// - 2: Latched
/// - 3: Reserved
#[bitfield_support]
#[repr(u8)]
#[derive(Clone, Copy, PartialEq, Eq)]
pub enum EventMode {
    // 0: Reserved (Single)
    /// 1: Multiple (SingleShot)
    SingleShot = 1,
    /// 2: Latched (Disappears)
    Disappears = 2,
    /// 3: Reserved (Appears)
    Appears = 3,
}

impl EventMode {
    /// Returns the default EventMode value (`SingleShot`).
    pub const fn new() -> Self {
        Self::SingleShot
    }
}

/// Represents a single entry in the Event memory as defined by IO-Link Specification v1.1.4.
///
/// Each event entry consists of:
/// - An [`EventQualifier`] describing the event's mode, type, source, and instance.
/// - An event code (`u16`) identifying the specific event (see device_event_code macro).
///
/// The event entry is stored in the event memory and can be serialized to a 3-byte representation
/// for transmission or storage.
///
/// # Fields
/// - `event_qualifier`: The event qualifier, encoding mode, type, source, and instance.
/// - `event_code`: The event code (u16), as per IO-Link event code definitions.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct EventEntry {
    /// Event qualifier (mode, type, source, instance)
    pub event_qualifier: EventQualifier,
    /// Event code (see device_event_code macro)
    pub event_code: u16,
}

impl EventEntry {
    /// Creates a new [`EventEntry`] with the given qualifier and code.
    ///
    /// # Arguments
    /// * `event_qualifier` - The event qualifier describing the event.
    /// * `event_code` - The event code (u16) as per IO-Link event code definitions.
    ///
    /// # Returns
    /// A new [`EventEntry`] instance.
    pub fn new(event_qualifier: EventQualifier, event_code: u16) -> Self {
        Self {
            event_qualifier,
            event_code,
        }
    }

    /// Converts the [`EventEntry`] into its 3-byte representation.
    ///
    /// The byte layout is as follows:
    /// - Byte 0: EventQualifier as a single byte (see [`EventQualifier::into_bits`])
    /// - Byte 1: Lower 8 bits of the event code
    /// - Byte 2: Upper 8 bits of the event code
    ///
    /// # Returns
    /// A `[u8; 3]` array containing the serialized event entry.
    pub fn to_bytes(&self) -> [u8; 3] {
        let mut bytes = [0u8; 3];
        bytes[0] = self.event_qualifier.into_bits();
        bytes[1] = (self.event_code & 0xFF) as u8;
        bytes[2] = ((self.event_code >> 8) & 0xFF) as u8;
        bytes
    }
}

/// All the Event Handler configuration states used
/// See Figure 56 – State machine of the Device Event handler
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum EhConfState {
    /// (Handler changed to the ACTIVE state)
    Active,
    /// (Handler changed to the INACTIVE state)
    Inactive,
}
